// Augment the auto-generated Cloudflare.Env (from worker-configuration.d.ts)
// with secrets configured via `wrangler secret` / .dev.vars.
//
// Bindings (D1, R2, KV, DO, Queue, vars) are auto-generated by `npm run cf-typegen`
// from wrangler.json. Only secrets need to be declared here.

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Cloudflare {
    interface Env {
      RSA_PRIVATE_KEY: string;
      ADMIN_TOKEN: string;
      RESEND_API_KEY: string;

      DUO_IKEY?: string;
      DUO_SKEY?: string;
      DUO_HOST?: string;
      YUBICO_CLIENT_ID?: string;
      YUBICO_SECRET_KEY?: string;
      PUSH_INSTALLATION_ID?: string;
      PUSH_INSTALLATION_KEY?: string;
    }
  }
}

type Env = Cloudflare.Env;
export type { Env };
