import { sqliteTable, text, integer, blob } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", {
  uuid: text("uuid").primaryKey(),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  verifiedAt: integer("verified_at", { mode: "timestamp" }),
  lastVerifyingAt: integer("last_verifying_at", { mode: "timestamp" }),
  loginVerifyCount: integer("login_verify_count").notNull().default(0),
  email: text("email").notNull().unique(),
  emailNew: text("email_new"),
  emailNewToken: text("email_new_token"),
  name: text("name").notNull(),
  passwordHash: blob("password_hash", { mode: "buffer" }).notNull(),
  salt: blob("salt", { mode: "buffer" }).notNull(),
  passwordIterations: integer("password_iterations").notNull(),
  passwordHint: text("password_hint"),
  akey: text("akey").notNull(),
  privateKey: text("private_key"),
  publicKey: text("public_key"),
  totpSecret: text("totp_secret"),
  totpRecover: text("totp_recover"),
  securityStamp: text("security_stamp").notNull(),
  stampException: text("stamp_exception"),
  equivalentDomains: text("equivalent_domains").notNull().default("[]"),
  excludedGlobals: text("excluded_globals").notNull().default("[]"),
  clientKdfType: integer("client_kdf_type").notNull().default(0),
  clientKdfIter: integer("client_kdf_iter").notNull().default(600000),
  clientKdfMemory: integer("client_kdf_memory"),
  clientKdfParallelism: integer("client_kdf_parallelism"),
  apiKey: text("api_key"),
  avatarColor: text("avatar_color"),
  externalId: text("external_id"),
});
